---
title: "My English Activity Log : MEAL"
author: 
  - name: "Dorio Luca" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  - "M.E.A.L."
output: distill::distill_article
---


• October 4th: I have start my blog today! For this I read a lot of articles in english, it is a first for me.

• October 30th: I read more and more english evey day, for my portfolio obviously but also for my pleasure now.

• November 10th: I’m starting to watch some series and video in english to devellop my audition because I am less good in this.

• December 09th: We are in examinations period so I didn't work a lot my english but I have a good excuse.

• February 03th: Now I have finished my exam so I can return to my English learning. For this I have started to write my last articles.

• March 14th: I participated in my first English remediation with Samuel. I didn't have the need to do this but my friend François convinced me to participate. That was very funny.

• April 10th: In one month i have my oral exam so every night before sleeping I read my portfolio in order to be prepared to this exam.



